//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HuntingFarm.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AccountingEvent
    {
        public int id { get; set; }
        public int ClientId { get; set; }
        public int HuntId { get; set; }
        public System.DateTime Date { get; set; }
    
        public virtual Hunting Hunting { get; set; }
        public virtual User User { get; set; }
    }
}
