//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HuntingFarm.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Hunting
    {
        public int id { get; set; }
        public string Name { get; set; }
        public int AnimalId { get; set; }
        public int HouseId { get; set; }
        public int ClientId { get; set; }
        public decimal Cost { get; set; }
    
        public virtual Animal Animal { get; set; }
        public virtual House House { get; set; }
        public virtual User User { get; set; }
    }
}
