//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HuntingFarm.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public User()
        {
            this.Huntings = new HashSet<Hunting>();
        }

        public User(string Name, string Surname, string Patronymic, System.DateTime Birthday, int RoleId, int GenderId, string Email, string Password, string Login, Nullable<int> Experience )
        {
            this.Name = Name;
            this.Surname = Surname;
            this.Patronymic = Patronymic;
            this.Birthday = Birthday;
            this.RoleId = RoleId;
            this.GenderId = GenderId;
            this.Email = Email;
            this.Password = Password;
            this.Login = Login;
            this.Experience = Experience;
        }

        public int id { get; set; }
        public string Name { get; set; }
        public string Surname { get; set; }
        public string Patronymic { get; set; }
        public Nullable<System.DateTime > Birthday { get; set; }
        public int RoleId { get; set; }
        public int GenderId { get; set; }
        public string Email { get; set; }
        public string Password { get; set; }
        public string Login { get; set; }
        public Nullable<int> Experience { get; set; }
    
        public virtual Gender Gender { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Hunting> Huntings { get; set; }
        public virtual Role Role { get; set; }
    }
}
